changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - feat
        - feature
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - refactor
        - ci
    - title: Other Changes
      labels:
        - "*"
